### ISSUE TITLE
Populate Command should use Repository::findAll() 

### ISSUE THREAD

**Issue by rugbymauri** [whatwedo/SearchBundle#14]
if the findAll() function filters the result. the PopulateCommand doesn't filter these entities.

```
public function findAll()
{
    $queryBuilder = $this->createQueryBuilder('m');
    $queryBuilder->where('m.isActive=true');
    return $queryBuilder->getQuery()->getResult();
}
```

other possibility is to define a "findAllEntitiesToIndex()" method on the Repo. And called instead of the findAll(), if defined.

**Comment by xarem** [comment]
@rugbymauri i don't think so. the controller (or whoever) will need to filter the response of the search bundle anyway, for example because of permissions. and if so then we should return a querybuilder instead of the results to iterate it, otherwise we will have memory issues

**Comment by tuxes3** [comment]
solved by using `CustomSearchPopulateQueryBuilderInterface` in your repository.
