### ISSUE TITLE
Error installing in Symfony 4.4.4

### ISSUE THREAD

**Issue by Koronos** [whatwedo/SearchBundle#20]
When I try to install the bundle, I got the next message in cache:clear script:

```
Cannot autowire service "whatwedo\SearchBundle\Manager\IndexManager": argument "$doctrine" of method "__construct()" references interface "Symfony\Bridge\Doctrine\RegistryInterface" but no such service exists. Try changing the type-hint to "Doctrine\Persistence\ManagerRegistry" instead.
```

I see a pull request making the change necessary to fix this issue, is going to be merged?

**Comment by tuxes3** [comment]
This bundle is still in development, a release will happen later on this year. If you wish to use the SearchBundle with symfony 6 and php 8 use this in your composer: `"whatwedo/search-bundle": "dev-3.0-dev as v3.0.0",`. 

Reopen a new issue if something is not clear.
