### ISSUE TITLE
Support other types of primary key?

### ISSUE THREAD

**Issue by hopeter1018** [whatwedo/SearchBundle#21]
May I know if this project have a plan to support other types of primary key such as:

Symfony uuid:
```
     * @ORM\Column(name="id", type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
```
&

Ramsey uuid-doctrine:
```
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
```

**Comment by xarem** [comment]
Hey @hopeter1018 

We won't add support for other types of primary keys because we're not using it in any project - but we're open for a PR.
