### ISSUE TITLE
Symfony\Bridge\Doctrine\RegistryInterface deprecated

### ISSUE THREAD

**Issue by Midor2Mid** [whatwedo/SearchBundle#22]
Symfony\Bridge\Doctrine\RegistryInterface now has been deprecated and have to use Doctrine\Persistence\ManagerRegistry instead, can we have an update on this ?

**Comment by xarem** [comment]
Hey @Midor2Mid 

Please use the branch symfony5. It's already fixed in this. you can add it as `dev-symfony5` in composer.

**Comment by tuxes3** [comment]
"whatwedo/search-bundle": "dev-3.0-dev as v3.0.0", as of now
